autoscale:
  image: 192.168.18.250:5002/training/rhel-autoscale
  environment:
    RANCHER_USER: "${apiname}"
    RANCHER_PASSWORD: "${apikey}"
    RANCHER_ENDPOINT: "${endpoint}"
    TARGET_SERVICE: "${targetservice}"
    SCALE_MIN: "${scalemin}"
    SCALE_MAX: "${scalemax}"
    SCALE_INTERVAL: "${interval}"
  command: python /monitor.py
