wp-lb:
  ports:
  - 8001:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - wordpress:wordpress
  stdin_open: true
wordpress:
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: rancher123
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: 192.168.18.250:5002/training/wordpress
  links:
  - mysql:db
  stdin_open: true
mysql:
  environment:
    MYSQL_ROOT_PASSWORD: rancher123
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: 192.168.18.250:5002/training/mysql
  stdin_open: true
