wp-lb:
  ports:
  - ${wp_port}:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - wordpress:wordpress
  stdin_open: true
wordpress:
  environment:
    WORDPRESS_DB_HOST: ${db_host}
    WORDPRESS_DB_USER: ${db_user}
    WORDPRESS_DB_PASSWORD: ${db_passwd}
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: 192.168.18.250:5002/training/wordpress
  links:
  - mysql:db
  stdin_open: true
mysql:
  environment:
    MYSQL_ROOT_PASSWORD: ${db_passwd}
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: 192.168.18.250:5002/training/mysql
  stdin_open: true
