.catalog:
  name: "wordpress"
  version: "1.0"
  description: "wordpress with your application deployed"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: wp_port
      description: "worpress port"
      label: "wp port"
      type: "int"
      required: true
      default: "8001"
    - variable: db_host
      description: "database host"
      label: "database host"
      type: "string"
      required: true
      default: "db:3306"
    - variable: db_user
      description: "database user"
      label: "database user"
      type: "string"
      required: true
      default: "root"
    - variable: db_passwd
      description: "database password"
      label: "database password"
      type: "string"
      required: true
wp-lb:
  scale: 1
  load_balancer_config:
    lb_cookie_stickiness_policy:
      cookie: test
      mode: insert
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
wordpress:
  scale: 2
mysql:
  scale: 1
