wp-lb:
  scale: 1
  load_balancer_config:
    lb_cookie_stickiness_policy:
      cookie: test
      mode: insert
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
wordpress:
  scale: 2
mysql:
  scale: 1
